### ISSUE TITLE
[bug] Creation of lakehouse fails

### ISSUE THREAD

**Issue by weiligao** [microsoft/terraform-provider-fabric#100]
### 🐛 What happened?

When trying to create a lakehouse inside a workspace, Terraform fails with the error
```
Error: create operation
  with fabric_lakehouse.demo,
  on fabric-lakehouse.tf line 3, in resource "fabric_lakehouse" "demo":
   3: resource "fabric_lakehouse" "demo" {
Could not create resource: The request has an invalid input
```

This is the Terraform code and plan:
```
resource "fabric_lakehouse" "demo" {
  display_name = "lh-demo"
  workspace_id = fabric_workspace.demo.id
}
```

```
Terraform will perform the following actions:
  # fabric_lakehouse.demo will be created
  + resource "fabric_lakehouse" "demo" {
      + description  = ""
      + display_name = "lh-demo"
      + id           = (known after apply)
      + properties   = (known after apply)
      + workspace_id = "4b411685-99af-46c5-9356-6086d07e125c"
    }
```

### 🌌 Environment (Provider Version)

0.1.0-beta.5

### 🌌 Environment (Terraform Version)

1.9.8

### 🌌 Environment (OS)

Linux

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by lharantes** [comment]
Try to remove the dash

**Comment by DariuszPorowski** [comment]
Hi @weiligao, as @lharantes mentioned, Lakehouse does not accept dash in the display name, even in UI.

![Image](https://github.com/user-attachments/assets/ae9f5f0c-d0f6-470b-8729-040e5ce3606d)

**Comment by weiligao** [comment]
Ok thanks a lot, I didn't know that... should have tried creating it in the UI first.
