### ISSUE TITLE
Timeline Fabric SQL DB

### ISSUE THREAD

**Issue by jonah-lottner-taod** [microsoft/terraform-provider-fabric#105]
### ☑️ Checklist

- [x] I've searched the project's [`issues`](../issues?q=is%3Aissue) and did not find answer for my question.

### ❓ Question

In the official MS decision guide on SQL DBs for Fabric, it is noted that Fabric SQL DBs can be deployed via this provider. Is there an ETA for this feature?

### 📎 Additional context

![Image](https://github.com/user-attachments/assets/d70eda33-9473-462f-a0bc-55d3cd6751f2)

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
@cisraeli @Halamish51 PTAL
ref: https://learn.microsoft.com/en-us/fabric/database/sql/decision-guide#databases

**Comment by jonah-lottner-taod** [comment]
Hi @DariuszPorowski 

thanks for inquiring!
