### ISSUE TITLE
[question] The Git provider type 'GitHub' is not supported

### ISSUE THREAD

**Issue by SemUijen** [microsoft/terraform-provider-fabric#108]
### ☑️ Checklist

- [x] I've searched the project's [`issues`](../issues?q=is%3Aissue) and did not find answer for my question.

### ❓ Question

Is it GitHub already supported by the terraform provider?
If yes, how to setup the provider details? (the required details shown in provider docs are for DevOps and not for GitHub)
If no, this question is actually a feature request

### 📎 Additional context

In the documentation (https://registry.terraform.io/providers/microsoft/fabric/latest/docs/resources/workspace_git) it shows that GitHub is already supported. When trying to deploy using GitHub as its provider type it returns. The Git provider type 'GitHub' is not supported. 
Looking at the Fabric Rest API Docs(https://learn.microsoft.com/en-us/rest/api/fabric/core/git/connect) the git provider details that are required (see terraform docs) are the details for azure DevOps. GitHub has different details.

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
Hi @SemUijen

It's a bug in the provider docs. Thanks for reporting. GitHub integration is not supported yet. Docs fix on the way: #109
