### ISSUE TITLE
Not Able to deploy Resources at the Same Time Using Different Auth Methods

### ISSUE THREAD

**Issue by kiyoungoh** [microsoft/terraform-provider-fabric#114]
### 🐛 What happened?

•	While deploying resources, due to the limitation of supported authentication method per resource, need to use two different authentication methods; 1. Service principal 2. User-context.
•	While deploying all the resources together, hitting the error below.

│ Error: create operation
│
│   with fabric_warehouse.warehouses["1-3"],
│   on main.tf line 228, in resource "fabric_warehouse" "warehouses":
│  228: resource "fabric_warehouse" "warehouses" {
│
│ Could not create resource: User is not authorized
╵

### 🔬 How to reproduce?

•	Noticed all the resources are being deployed at the same time for both authentication methods.
•	We tried to separate the user-context based resources and observed the issue would only happen when trying to deploy all the resources for both authentication methods. There was no issue when deploying the same user-context based resources totally separately. 

### 🌌 Environment (Provider Version)

v0.1.0-beta.5

### 🌌 Environment (Terraform Version)

1.9.8

### 🌌 Environment (OS)

Linux

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
Hi @kiyoungoh 

The provider supports only one auth metod at time. The workaround (before Fabric starts fully supporting SPN) is to create multi-module deployment with auth context switching between modules run.

p.s.
Changed classification from bug to question because it's not a bug.
