### ISSUE TITLE
[bug] fabric_lakehouse resource not working with Service Principal Secret authentication

### ISSUE THREAD

**Issue by ottojaaskelainen** [microsoft/terraform-provider-fabric#41]
### 🐛 What happened?

Currently fabric_lakehouse resource can't be deployed when using Service Principal Client Secret authentication. I'm quite sure the reason is that wrong scopes are used when generating a token for SP to be consumed in the API calls under the hood. 

Currently when trying to deploy, first it gives you an error: 

"Could not create resource: An unexpected error occurred while processing the request"

And if you try second time: 

Could not create resource: Requested '{lakehouse_name}' is already in use

Anyways the lakehouse does not get created and after a while, you can again try with the same name and you end up to the first error. The name is just cached for a while somewhere as reserved.

I have been playing around with Fabric REST APIs and had this same issue when was using wrong scope for token generation. The correct ones to use are:

"https://api.fabric.microsoft.com/Workspace.ReadWrite.All/.default" and "https://api.fabric.microsoft.com/Item.ReadWrite.All/.default"

After using those I'm able to create lakehouses through Service Principal authentication

### 🌌 Environment (Provider Version)

0.1.0-beta.4

### 🌌 Environment (Terraform Version)

1.9.7

### 🌌 Environment (OS)

macOS

### 🔰 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by ottojaaskelainen** [comment]
Same issue seems to be in place also with azure cli authentication.

**Comment by DariuszPorowski** [comment]
Hi @ottojaaskelainen Scopes are used only for the user authentication, not for the Service Principals: https://github.com/microsoft/terraform-provider-fabric/blob/main/docs/guides/auth_app_reg_user.md

For the Service Principal you do not setting scopes in the app registration. Below guides will help you correctly configure Entra App for client/secret authentication:
- How to setup app for SPN auth: https://github.com/microsoft/terraform-provider-fabric/blob/main/docs/guides/auth_app_reg_spn.md
- Authenticating using a Service Principal and Client Secret https://github.com/microsoft/terraform-provider-fabric/blob/main/docs/guides/auth_spn_secret.md

**Comment by DariuszPorowski** [comment]
@ottojaaskelainen may you share your hcl terraform code for the lakehouse? I cannot repo this issue.

**Comment by DariuszPorowski** [comment]
Thank you @ottojaaskelainen

I identified the bug. The problem was not in the SPN auth, but when `configuration.enable_schemas` value was `false` (with `true` works) 

Failing configuration:
```terraform
resource "fabric_lakehouse" "example" {
  display_name = "example"
  description  = "example"
  workspace_id = "00000000-0000-0000-0000-000000000000"

  configuration = {
    enable_schemas = false
  }
}
```

To create lakehouse without schemas currently, the working hcl is skipping `configuration` attribute. 
```terraform
resource "fabric_lakehouse" "example" {
  display_name = "example"
  description  = "example"
  workspace_id = "00000000-0000-0000-0000-000000000000"
}
```

The fix is on the way: https://github.com/microsoft/terraform-provider-fabric/pull/47 and will be addressed in the next release.

**Comment by ottojaaskelainen** [comment]
Hey, that's true, can create lakehouses without configuration attribute! Great that the origin of issue was found !
