### ISSUE TITLE
Using GitHub Actions to Build Fabric Data Pipelines with Terraform

### ISSUE THREAD

**Issue by dogaerdik** [microsoft/terraform-provider-fabric#77]
### ☑️ Checklist

- [x] I've searched the project's [`issues`](../issues?q=is%3Aissue) and did not find answer for my question.

### ❓ Question

How can I create a Fabric data pipeline using GitHub Actions with Terraform? I can create notebooks, lakehouses, and other Fabric components that authenticate with service principal authentication. However, the documentation is insufficient for service context authentication and creating a Fabric data pipeline. I haven't succeeded in achieving service context authentication with Terraform.

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
Hi @dogaerdik

Data Pipeline has not support Service Principal authentication yet and this is highlighted in the documentation already:

![Image](https://github.com/user-attachments/assets/42f1ad29-6b5f-433e-b8bf-2b2df1247aa7)

ref: https://registry.terraform.io/providers/microsoft/fabric/latest/docs/resources/data_pipeline

**Comment by DariuszPorowski** [comment]
Hi @dogaerdik

Azure CLI caches auth token, and Provider can use the cached token. This only works on the "local developer" scenario. If you think about automation via GH, AzDO, etc. this scenario is not applicable. All we have to do is wait until Fabric's API for Data Pipeline allows the use of SP auth (it's not Provider limitation itself).
